Document: gravity
Title: Debian gravity Manual
Author: <insert document author here>
Abstract: This manual describes what gravity is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gravity/gravity.sgml.gz

Format: postscript
Files: /usr/share/doc/gravity/gravity.ps.gz

Format: text
Files: /usr/share/doc/gravity/gravity.text.gz

Format: HTML
Index: /usr/share/doc/gravity/html/index.html
Files: /usr/share/doc/gravity/html/*.html
